package com.lx.iruanmi.bingwallpaper.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table BING.
 */
public class Bing {

    public Long id;
    @SerializedName("ID")
    public String ID;
    /**
     * Not-null value.
     */
    @SerializedName("bing_date")
    public String bing_date;
    /**
     * Not-null value.
     */
    @SerializedName("bing_country")
    public String bing_country;
    @SerializedName("bing_picname")
    public String bing_picname;
    @SerializedName("bing_maxpix")
    public String bing_maxpix;
    @SerializedName("bing_16x9")
    public String bing_16x9;
    @SerializedName("bing_9x16")
    public String bing_9x16;
    @SerializedName("bing_9x15")
    public String bing_9x15;
    @SerializedName("bing_copyright")
    public String bing_copyright;

    public Bing() {
    }

    public Bing(Long id) {
        this.id = id;
    }

    public Bing(Long id, String ID, String bing_date, String bing_country, String bing_picname, String bing_maxpix, String bing_16x9, String bing_9x16, String bing_9x15, String bing_copyright) {
        this.id = id;
        this.ID = ID;
        this.bing_date = bing_date;
        this.bing_country = bing_country;
        this.bing_picname = bing_picname;
        this.bing_maxpix = bing_maxpix;
        this.bing_16x9 = bing_16x9;
        this.bing_9x16 = bing_9x16;
        this.bing_9x15 = bing_9x15;
        this.bing_copyright = bing_copyright;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    /**
     * Not-null value.
     */
    public String getBing_date() {
        return bing_date;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setBing_date(String bing_date) {
        this.bing_date = bing_date;
    }

    /**
     * Not-null value.
     */
    public String getBing_country() {
        return bing_country;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setBing_country(String bing_country) {
        this.bing_country = bing_country;
    }

    public String getBing_picname() {
        return bing_picname;
    }

    public void setBing_picname(String bing_picname) {
        this.bing_picname = bing_picname;
    }

    public String getBing_maxpix() {
        return bing_maxpix;
    }

    public void setBing_maxpix(String bing_maxpix) {
        this.bing_maxpix = bing_maxpix;
    }

    public String getBing_16x9() {
        return bing_16x9;
    }

    public void setBing_16x9(String bing_16x9) {
        this.bing_16x9 = bing_16x9;
    }

    public String getBing_9x16() {
        return bing_9x16;
    }

    public void setBing_9x16(String bing_9x16) {
        this.bing_9x16 = bing_9x16;
    }

    public String getBing_9x15() {
        return bing_9x15;
    }

    public void setBing_9x15(String bing_9x15) {
        this.bing_9x15 = bing_9x15;
    }

    public String getBing_copyright() {
        return bing_copyright;
    }

    public void setBing_copyright(String bing_copyright) {
        this.bing_copyright = bing_copyright;
    }

    @Override
    public String toString() {
        return "Bing{" +
                "id=" + id +
                ", ID='" + ID + '\'' +
                ", bing_date='" + bing_date + '\'' +
                ", bing_country='" + bing_country + '\'' +
                ", bing_picname='" + bing_picname + '\'' +
                ", bing_maxpix='" + bing_maxpix + '\'' +
                ", bing_16x9='" + bing_16x9 + '\'' +
                ", bing_9x16='" + bing_9x16 + '\'' +
                ", bing_9x15='" + bing_9x15 + '\'' +
                ", bing_copyright='" + bing_copyright + '\'' +
                '}';
    }
}
