package com.lx.iruanmi.bingwallpaper.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BING.
 */
public class Bing {

    private Long id;
    private String ID;
    /** Not-null value. */
    private String bing_date;
    /** Not-null value. */
    private String bing_country;
    private String bing_picname;
    private String bing_maxpix;
    private String bing_16x9;
    private String bing_9x16;
    private String bing_9x15;
    private String bing_copyright;

    public Bing() {
    }

    public Bing(Long id) {
        this.id = id;
    }

    public Bing(Long id, String ID, String bing_date, String bing_country, String bing_picname, String bing_maxpix, String bing_16x9, String bing_9x16, String bing_9x15, String bing_copyright) {
        this.id = id;
        this.ID = ID;
        this.bing_date = bing_date;
        this.bing_country = bing_country;
        this.bing_picname = bing_picname;
        this.bing_maxpix = bing_maxpix;
        this.bing_16x9 = bing_16x9;
        this.bing_9x16 = bing_9x16;
        this.bing_9x15 = bing_9x15;
        this.bing_copyright = bing_copyright;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    /** Not-null value. */
    public String getBing_date() {
        return bing_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBing_date(String bing_date) {
        this.bing_date = bing_date;
    }

    /** Not-null value. */
    public String getBing_country() {
        return bing_country;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBing_country(String bing_country) {
        this.bing_country = bing_country;
    }

    public String getBing_picname() {
        return bing_picname;
    }

    public void setBing_picname(String bing_picname) {
        this.bing_picname = bing_picname;
    }

    public String getBing_maxpix() {
        return bing_maxpix;
    }

    public void setBing_maxpix(String bing_maxpix) {
        this.bing_maxpix = bing_maxpix;
    }

    public String getBing_16x9() {
        return bing_16x9;
    }

    public void setBing_16x9(String bing_16x9) {
        this.bing_16x9 = bing_16x9;
    }

    public String getBing_9x16() {
        return bing_9x16;
    }

    public void setBing_9x16(String bing_9x16) {
        this.bing_9x16 = bing_9x16;
    }

    public String getBing_9x15() {
        return bing_9x15;
    }

    public void setBing_9x15(String bing_9x15) {
        this.bing_9x15 = bing_9x15;
    }

    public String getBing_copyright() {
        return bing_copyright;
    }

    public void setBing_copyright(String bing_copyright) {
        this.bing_copyright = bing_copyright;
    }

}
